<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 2008 R2" host="IDC1-VM-UFT12"><DocLocation><![CDATA[C:\Users\utpal\Desktop\CI_App\FlightApp_UI]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[FlightApp_UI]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:28]]></Time>
<TimeTick>1521050908</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Users\utpal\.jenkins\workspace\Build_Generate\FlightEXE\FlightApp\FlightApp\bin\Debug\FlightApp.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Users\utpal\.jenkins\workspace\Build_Generate\FlightEXE\FlightApp\FlightApp\bin\Debug\FlightApp.exe",1]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:28]]></Time>
<TimeTick>1521050908</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Login" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Users\utpal\.jenkins\workspace\Build_Generate\FlightEXE\FlightApp\FlightApp\bin\Debug\FlightApp.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Login" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:28]]></Time>
<TimeTick>1521050908</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[txtUser.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:28]]></Time>
<TimeTick>1521050908</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Login" SourceLine="-1" >
<Disp><![CDATA[txtUser.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[txtUser.SetValue]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:28]]></Time>
<TimeTick>1521050908</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Login" SourceLine="-1" >
<Disp><![CDATA[txtUser.SetValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[txtPass.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:28]]></Time>
<TimeTick>1521050908</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Login" SourceLine="-1" >
<Disp><![CDATA[txtPass.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[txtPass.SetValue]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:29]]></Time>
<TimeTick>1521050909</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" Source="Login" SourceLine="-1" >
<Disp><![CDATA[txtPass.SetValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:29]]></Time>
<TimeTick>1521050909</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Login" SourceLine="-1" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:29]]></Time>
<TimeTick>1521050909</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Login" SourceLine="-1" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Login" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/14/2018 - 23:38:28" eTime="3/14/2018 - 23:38:29" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[Flight_Booking]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Booking]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:36]]></Time>
<TimeTick>1521050916</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[One way.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:36]]></Time>
<TimeTick>1521050916</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[One way.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Booking]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Select radio button]]></Obj>
<Details ><![CDATA[One way button is not selected.]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:36]]></Time>
<TimeTick>1521050916</TimeTick>
<NodeArgs eType="User" icon="10" nRep="27" status="Failed" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Select radio button]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Booking]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:36]]></Time>
<TimeTick>1521050916</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[cmbFrom.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:36]]></Time>
<TimeTick>1521050916</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[cmbFrom.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[cmbFrom.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:39]]></Time>
<TimeTick>1521050919</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="31" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[cmbFrom.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[cmbTo.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:39]]></Time>
<TimeTick>1521050919</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[cmbTo.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[cmbTo.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:41]]></Time>
<TimeTick>1521050921</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="34" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[cmbTo.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[cmbTicket.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:42]]></Time>
<TimeTick>1521050922</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="35" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[cmbTicket.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[cmbTicket.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:44]]></Time>
<TimeTick>1521050924</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="37" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[cmbTicket.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[dTPicker.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:44]]></Time>
<TimeTick>1521050924</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[dTPicker.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[dTPicker.SetValue]]></Obj>
<Details plainTxt="False" ><![CDATA["13/4/2018"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:45]]></Time>
<TimeTick>1521050925</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[dTPicker.SetValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[To]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAComboBox]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:45]]></Time>
<TimeTick>1521050925</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[To.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:45]]></Time>
<TimeTick>1521050925</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[To.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[To.SetValue]]></Obj>
<Details plainTxt="False" ><![CDATA["Economy"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:45]]></Time>
<TimeTick>1521050925</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[To.SetValue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="41" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[To]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Find Flight.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:45]]></Time>
<TimeTick>1521050925</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="45" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Find Flight.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Find Flight.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:46]]></Time>
<TimeTick>1521050926</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="47" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Find Flight.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Book.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:46]]></Time>
<TimeTick>1521050926</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Book.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Book.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:47]]></Time>
<TimeTick>1521050927</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="50" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Book.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Window]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:47]]></Time>
<TimeTick>1521050927</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:47]]></Time>
<TimeTick>1521050927</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:48]]></Time>
<TimeTick>1521050928</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="51" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Window]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Booking.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:48]]></Time>
<TimeTick>1521050928</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Booking.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Booking.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/14/2018 - 23:38:53]]></Time>
<TimeTick>1521050933</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Booking.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="28" Source="Flight_Booking" SourceLine="-1" >
<Disp><![CDATA[Booking]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/14/2018 - 23:38:29" eTime="3/14/2018 - 23:38:53" passed="0" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="23" status="Failed" >
<Disp><![CDATA[Flight_Booking Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[FlightApp_UI Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="3/14/2018 - 23:38:28" eTime="3/14/2018 - 23:38:53" passed="1" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test FlightApp_UI Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>